version: '3.8'

services:
  llama-cpp-studio:
    build:
      context: .
      args:
        BUILD_FRONTEND: "true"
    ports:
      - "8080:8080"
      - "2000:2000"
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend
    environment:
      - CUDA_VISIBLE_DEVICES=""
      - HF_HUB_ENABLE_HF_TRANSFER=1
      # Uncomment and set your HuggingFace API key to enable model search and download
      # - HUGGINGFACE_API_KEY=
    # Alternative: Use .env file for environment variables
    # env_file:
    #   - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
