version: '3.8'

services:
  llama-cpp-studio:
    build: .
    ports:
      - "8080:8080"
      - "2000:2000"
    volumes:
      - ./data:/app/data
    environment:
      - CUDA_VISIBLE_DEVICES=all
      - HF_HUB_ENABLE_HF_TRANSFER=1
      # Uncomment and set your HuggingFace API key to enable model search and download
      # - HUGGINGFACE_API_KEY=your_huggingface_token_here
    # Alternative: Use .env file for environment variables
    # env_file:
    #   - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
