/** Real task shapes emitted by backend task-start routes (mirrors backend integration tests). */

export const REAL_TASK_FIXTURES = [
  {
    label: 'build from source',
    task: {
      task_id: 'build_source-main-1700000000_1700000000',
      type: 'build',
      status: 'running',
      progress: 12,
      description: 'Build llama.cpp main',
      metadata: { engine: 'llama_cpp' },
    },
    cancelEndpoint: '/api/llama-versions/build-cancel',
  },
  {
    label: 'branch sync build',
    task: {
      task_id: 'build_sync_source-main_1700000000',
      type: 'build',
      status: 'running',
      progress: 5,
      description: 'Sync llama.cpp main',
      metadata: { sync: true },
    },
    cancelEndpoint: '/api/llama-versions/build-cancel',
  },
  {
    label: 'gguf download',
    task: {
      task_id: 'download_gguf_org_model_Q4_K_M_1700000000123',
      type: 'download',
      status: 'running',
      progress: 33,
      description: 'Download model-Q4_K_M.gguf',
      metadata: { huggingface_id: 'org/model', filename: 'model-Q4_K_M.gguf', quantization: 'Q4_K_M' },
    },
    cancelEndpoint: '/api/models/downloads/cancel',
  },
  {
    label: 'safetensors download',
    task: {
      task_id: 'download_safetensors_org_model_model_1700000000123',
      type: 'download',
      status: 'running',
      progress: 20,
      description: 'Download model.safetensors',
      metadata: { huggingface_id: 'org/model', filename: 'model.safetensors' },
    },
    cancelEndpoint: '/api/models/downloads/cancel',
  },
  {
    label: 'safetensors bundle download',
    task: {
      task_id: 'download_safetensors_bundle_org_repo_1700000000123',
      type: 'download',
      status: 'running',
      progress: 15,
      description: 'Safetensors bundle',
      metadata: { huggingface_id: 'org/repo' },
    },
    cancelEndpoint: '/api/models/downloads/cancel',
  },
  {
    label: 'gguf bundle download',
    task: {
      task_id: 'download_gguf_bundle_org_repo_Q4_K_M_1700000000123',
      type: 'download',
      status: 'running',
      progress: 18,
      description: 'GGUF bundle',
      metadata: { huggingface_id: 'org/repo', quantization: 'Q4_K_M' },
    },
    cancelEndpoint: '/api/models/downloads/cancel',
  },
  {
    label: 'projector download',
    task: {
      task_id: 'download_projector_org--model--Q4_K_M_mmproj-F16_1700000000123',
      type: 'download',
      status: 'running',
      progress: 8,
      description: 'Projector mmproj-F16.gguf',
      metadata: { huggingface_id: 'org/model', filename: 'mmproj-F16.gguf', model_id: 'org--model--Q4_K_M' },
    },
    cancelEndpoint: '/api/models/downloads/cancel',
  },
  {
    label: 'cuda install',
    task: {
      task_id: 'install_cuda_install_1700000000123',
      type: 'install',
      status: 'running',
      progress: 10,
      description: 'CUDA install',
      metadata: { manager: 'cuda', operation: 'install' },
    },
    cancelEndpoint: '/api/llama-versions/cuda/cancel',
  },
  {
    label: 'cuda uninstall',
    task: {
      task_id: 'install_cuda_uninstall_1700000000456',
      type: 'install',
      status: 'running',
      progress: 10,
      description: 'CUDA uninstall',
      metadata: { manager: 'cuda', operation: 'uninstall' },
    },
    cancelEndpoint: '/api/llama-versions/cuda/cancel',
  },
  {
    label: 'lmdeploy install',
    task: {
      task_id: 'install_lmdeploy_install_1700000000456',
      type: 'install',
      status: 'running',
      progress: 10,
      description: 'LMDeploy install',
      metadata: { manager: 'lmdeploy', operation: 'install' },
    },
    cancelEndpoint: '/api/lmdeploy/cancel',
  },
  {
    label: 'lmdeploy install source',
    task: {
      task_id: 'install_lmdeploy_install_source_1700000000456',
      type: 'install',
      status: 'running',
      progress: 10,
      description: 'LMDeploy install from source',
      metadata: { manager: 'lmdeploy', operation: 'install_source' },
    },
    cancelEndpoint: '/api/lmdeploy/cancel',
  },
  {
    label: 'lmdeploy sync source',
    task: {
      task_id: 'install_lmdeploy_sync_source_1700000000456',
      type: 'install',
      status: 'running',
      progress: 10,
      description: 'LMDeploy sync',
      metadata: { manager: 'lmdeploy', operation: 'sync_source', sync: true },
    },
    cancelEndpoint: '/api/lmdeploy/cancel',
  },
  {
    label: 'lmdeploy remove',
    task: {
      task_id: 'install_lmdeploy_remove_1700000000456',
      type: 'install',
      status: 'running',
      progress: 10,
      description: 'LMDeploy remove',
      metadata: { manager: 'lmdeploy', operation: 'remove' },
    },
    cancelEndpoint: '/api/lmdeploy/cancel',
  },
  {
    label: '1cat-vllm install',
    task: {
      task_id: 'install_onecat_vllm_install_1700000000789',
      type: 'install',
      status: 'running',
      progress: 10,
      description: '1Cat-vLLM install',
      metadata: { manager: 'onecat_vllm', operation: 'install' },
    },
    cancelEndpoint: '/api/1cat-vllm/cancel',
  },
  {
    label: '1cat-vllm install source',
    task: {
      task_id: 'install_onecat_vllm_install_source_1700000000789',
      type: 'install',
      status: 'running',
      progress: 10,
      description: '1Cat-vLLM install from source',
      metadata: { manager: 'onecat_vllm', operation: 'install_source' },
    },
    cancelEndpoint: '/api/1cat-vllm/cancel',
  },
  {
    label: '1cat-vllm sync source',
    task: {
      task_id: 'install_onecat_vllm_sync_source_1700000000789',
      type: 'install',
      status: 'running',
      progress: 10,
      description: '1Cat-vLLM sync',
      metadata: { manager: 'onecat_vllm', operation: 'sync_source', sync: true },
    },
    cancelEndpoint: '/api/1cat-vllm/cancel',
  },
  {
    label: '1cat-vllm remove',
    task: {
      task_id: 'install_onecat_vllm_remove_1700000000789',
      type: 'install',
      status: 'running',
      progress: 10,
      description: '1Cat-vLLM remove',
      metadata: { manager: 'onecat_vllm', operation: 'remove' },
    },
    cancelEndpoint: '/api/1cat-vllm/cancel',
  },
]

export const FORBIDDEN_PATTERNS = [
  /\bcuda_operation\b/,
  /\blmdeploy_operation\b/,
  /\bonecat_vllm_operation\b/,
  /\/api\/tasks\/cancel/,
  /metadata\.target/,
  /metadata-key=["']target["']/,
  /normalizeCudaTask/,
  /normalizeLmdeployTask/,
  /normalizeOnecatTask/,
]
