"""Shared request-default field specs for audio.cpp family profiles."""

from __future__ import annotations

from typing import Any, Dict

FIELD_SPECS: Dict[str, Dict[str, Any]] = {
    "text": {
        "key": "text",
        "label": "Text / prompt",
        "type": "textarea",
        "placeholder": "Input text or prompt…",
        "request_field": "text",
    },
    "target_text": {
        "key": "target_text",
        "label": "Target text",
        "type": "textarea",
        "placeholder": "Target lyrics or speech…",
        "request_field": "target_text",
    },
    "lyrics": {
        "key": "lyrics",
        "label": "Lyrics",
        "type": "textarea",
        "placeholder": "Vocal lyrics…",
        "request_field": "lyrics",
    },
    "tags": {
        "key": "tags",
        "label": "Style tags",
        "type": "string",
        "placeholder": "pop,bright,drums",
        "options_key": "tags",
        "nested": True,
    },
    "language": {
        "key": "language",
        "label": "Language",
        "type": "string",
        "placeholder": "en",
        "request_field": "language",
    },
    "prompt": {
        "key": "prompt",
        "label": "ASR prompt / context",
        "type": "textarea",
        "placeholder": "Transcribe the speech.",
        "request_field": "prompt",
        "options_key": "text",
        "nested": True,
    },
    "transcript": {
        "key": "transcript",
        "label": "Exact transcript",
        "type": "textarea",
        "placeholder": "The exact transcript to align…",
        "request_field": "text",
    },
    "speaker": {
        "key": "speaker",
        "label": "Built-in speaker",
        "type": "string",
        "placeholder": "Vivian",
        "request_field": "speaker",
    },
    "instructions": {
        "key": "instructions",
        "label": "Voice design instructions",
        "type": "textarea",
        "placeholder": "A warm adult narrator",
        "request_field": "instructions",
        "options_key": "instruct",
        "nested": True,
    },
    "voice_id": {
        "key": "voice_id",
        "label": "Built-in voice id",
        "type": "string",
        "placeholder": "af_heart",
        "preset_field": True,
    },
    "voice_ref": {
        "key": "voice_ref",
        "label": "Reference audio (WAV)",
        "type": "path",
        "placeholder": "samples/reference.wav",
        "preset_field": True,
        "request_field": "voice_ref",
    },
    "target_voice": {
        "key": "target_voice",
        "label": "Target voice (WAV)",
        "type": "path",
        "placeholder": "target_voice.wav",
        "request_field": "target_voice",
    },
    "reference_text": {
        "key": "reference_text",
        "label": "Reference transcript",
        "type": "textarea",
        "placeholder": "Transcript matching the reference audio…",
        "preset_field": True,
        "request_field": "reference_text",
    },
    "style_ref_text": {
        "key": "style_ref_text",
        "label": "Style reference transcript",
        "type": "textarea",
        "placeholder": "Transcript of the style reference…",
        "request_field": "style_ref_text",
        "options_key": "style_ref_text",
        "nested": True,
    },
    "audio": {
        "key": "audio",
        "label": "Input audio (WAV)",
        "type": "path",
        "placeholder": "input.wav",
        "request_field": "audio",
    },
    "source_audio": {
        "key": "source_audio",
        "label": "Source audio (WAV)",
        "type": "path",
        "placeholder": "source.wav",
        "request_field": "source_audio",
    },
    "prosody_ref": {
        "key": "prosody_ref",
        "label": "Prosody / melody reference",
        "type": "path",
        "placeholder": "melody.wav",
        "request_field": "prosody_ref",
    },
    "style_ref": {
        "key": "style_ref",
        "label": "Style reference audio",
        "type": "path",
        "placeholder": "style.wav",
        "request_field": "style_ref",
    },
    "voice": {
        "key": "voice",
        "label": "Preset or built-in voice",
        "type": "string",
        "placeholder": "assistant",
        "request_field": "voice",
    },
    "task_route": {
        "key": "task_route",
        "label": "Task route",
        "type": "string",
        "placeholder": "text2music",
        "request_field": "task_route",
        "options_key": "task_route",
        "nested": True,
    },
    "stream": {
        "key": "stream",
        "label": "Stream partial output",
        "type": "bool",
        "request_field": "stream",
    },
    "duration_seconds": {
        "key": "duration_seconds",
        "label": "Duration (seconds)",
        "type": "float",
        "request_field": "duration_seconds",
        "options_key": "duration_seconds",
        "nested": True,
    },
    "target_duration_seconds": {
        "key": "target_duration_seconds",
        "label": "Target duration (seconds)",
        "type": "float",
        "request_field": "target_duration_seconds",
    },
    "repaint_start": {
        "key": "repaint_start",
        "label": "Repaint start (s)",
        "type": "float",
        "request_field": "repaint_start",
    },
    "repaint_end": {
        "key": "repaint_end",
        "label": "Repaint end (s)",
        "type": "float",
        "request_field": "repaint_end",
    },
    "repaint_mode": {
        "key": "repaint_mode",
        "label": "Repaint mode",
        "type": "string",
        "placeholder": "balanced",
        "options_key": "repaint_mode",
        "nested": True,
    },
    "repaint_strength": {
        "key": "repaint_strength",
        "label": "Repaint strength",
        "type": "float",
        "options_key": "repaint_strength",
        "nested": True,
    },
    "seed": {
        "key": "seed",
        "label": "Seed",
        "type": "int",
        "request_field": "seed",
        "options_key": "seed",
        "nested": True,
    },
    "temperature": {
        "key": "temperature",
        "label": "Temperature",
        "type": "float",
        "request_field": "temperature",
        "options_key": "temperature",
        "nested": True,
    },
    "top_p": {
        "key": "top_p",
        "label": "Top P",
        "type": "float",
        "request_field": "top_p",
        "options_key": "top_p",
        "nested": True,
    },
    "top_k": {
        "key": "top_k",
        "label": "Top K",
        "type": "int",
        "request_field": "top_k",
        "options_key": "top_k",
        "nested": True,
    },
    "max_tokens": {
        "key": "max_tokens",
        "label": "Max tokens",
        "type": "int",
        "request_field": "max_tokens",
        "options_key": "max_tokens",
        "nested": True,
    },
    "guidance_scale": {
        "key": "guidance_scale",
        "label": "Guidance scale",
        "type": "float",
        "request_field": "guidance_scale",
        "options_key": "guidance_scale",
        "nested": True,
    },
    "num_inference_steps": {
        "key": "num_inference_steps",
        "label": "Inference steps",
        "type": "int",
        "request_field": "num_inference_steps",
        "options_key": "num_inference_steps",
        "nested": True,
    },
    "repetition_penalty": {
        "key": "repetition_penalty",
        "label": "Repetition penalty",
        "type": "float",
        "request_field": "repetition_penalty",
        "options_key": "repetition_penalty",
        "nested": True,
    },
    "text_chunk_size": {
        "key": "text_chunk_size",
        "label": "Text chunk size",
        "type": "int",
        "options_key": "text_chunk_size",
        "nested": True,
    },
    "do_sample": {
        "key": "do_sample",
        "label": "Stochastic sampling",
        "type": "bool",
        "options_key": "do_sample",
        "nested": True,
    },
    "num_beams": {
        "key": "num_beams",
        "label": "Beam count",
        "type": "int",
        "options_key": "num_beams",
        "nested": True,
    },
    "audio_chunk_mode": {
        "key": "audio_chunk_mode",
        "label": "Audio chunk mode",
        "type": "string",
        "placeholder": "auto",
        "options_key": "audio_chunk_mode",
        "nested": True,
    },
    "audio_chunk_seconds": {
        "key": "audio_chunk_seconds",
        "label": "Audio chunk seconds",
        "type": "float",
        "options_key": "audio_chunk_seconds",
        "nested": True,
    },
    "vad_chunk_max_seconds": {
        "key": "vad_chunk_max_seconds",
        "label": "VAD chunk max (s)",
        "type": "float",
        "request_field": "vad_chunk_max_seconds",
    },
    "vad_chunk_merge_gap_seconds": {
        "key": "vad_chunk_merge_gap_seconds",
        "label": "VAD merge gap (s)",
        "type": "float",
        "request_field": "vad_chunk_merge_gap_seconds",
    },
    "vad_chunk_padding_seconds": {
        "key": "vad_chunk_padding_seconds",
        "label": "VAD padding (s)",
        "type": "float",
        "request_field": "vad_chunk_padding_seconds",
    },
    "threshold": {
        "key": "threshold",
        "label": "Detection threshold",
        "type": "float",
        "options_key": "threshold",
        "nested": True,
    },
    "neg_threshold": {
        "key": "neg_threshold",
        "label": "Negative threshold",
        "type": "float",
        "options_key": "neg_threshold",
        "nested": True,
    },
    "min_speech_duration_ms": {
        "key": "min_speech_duration_ms",
        "label": "Min speech duration (ms)",
        "type": "int",
        "options_key": "min_speech_duration_ms",
        "nested": True,
    },
    "min_silence_duration_ms": {
        "key": "min_silence_duration_ms",
        "label": "Min silence duration (ms)",
        "type": "int",
        "options_key": "min_silence_duration_ms",
        "nested": True,
    },
    "speech_pad_ms": {
        "key": "speech_pad_ms",
        "label": "Speech padding (ms)",
        "type": "int",
        "options_key": "speech_pad_ms",
        "nested": True,
    },
    "track_name": {
        "key": "track_name",
        "label": "Track name",
        "type": "string",
        "placeholder": "vocals",
        "options_key": "track_name",
        "nested": True,
    },
    "negative_prompt": {
        "key": "negative_prompt",
        "label": "Negative prompt",
        "type": "textarea",
        "options_key": "negative_prompt",
        "nested": True,
    },
    "audio_input_kind": {
        "key": "audio_input_kind",
        "label": "Audio input kind",
        "type": "string",
        "placeholder": "init_audio",
        "options_key": "audio_input_kind",
        "nested": True,
    },
    "init_noise_level": {
        "key": "init_noise_level",
        "label": "Init noise level",
        "type": "float",
        "options_key": "init_noise_level",
        "nested": True,
    },
    "inpaint_mask_start_seconds": {
        "key": "inpaint_mask_start_seconds",
        "label": "Inpaint mask start (s)",
        "type": "string",
        "placeholder": "2.5,6.5",
        "options_key": "inpaint_mask_start_seconds",
        "nested": True,
    },
    "inpaint_mask_end_seconds": {
        "key": "inpaint_mask_end_seconds",
        "label": "Inpaint mask end (s)",
        "type": "string",
        "placeholder": "3.5,8.0",
        "options_key": "inpaint_mask_end_seconds",
        "nested": True,
    },
    "sampler": {
        "key": "sampler",
        "label": "Sampler",
        "type": "string",
        "placeholder": "pingpong",
        "options_key": "sampler",
        "nested": True,
    },
    "infinite_mode": {
        "key": "infinite_mode",
        "label": "Infinite mode",
        "type": "bool",
        "options_key": "infinite_mode",
        "nested": True,
    },
    "codec_duration": {
        "key": "codec_duration",
        "label": "Codec duration (s)",
        "type": "float",
        "options_key": "codec_duration",
        "nested": True,
    },
    "codec_guidance_scale": {
        "key": "codec_guidance_scale",
        "label": "Codec guidance scale",
        "type": "float",
        "options_key": "codec_guidance_scale",
        "nested": True,
    },
    "length_adjust": {
        "key": "length_adjust",
        "label": "Length adjust",
        "type": "float",
        "options_key": "length_adjust",
        "nested": True,
    },
    "intelligibility_cfg_rate": {
        "key": "intelligibility_cfg_rate",
        "label": "Intelligibility CFG",
        "type": "float",
        "options_key": "intelligibility_cfg_rate",
        "nested": True,
    },
    "similarity_cfg_rate": {
        "key": "similarity_cfg_rate",
        "label": "Similarity CFG",
        "type": "float",
        "options_key": "similarity_cfg_rate",
        "nested": True,
    },
    "inference_cfg_rate": {
        "key": "inference_cfg_rate",
        "label": "Inference CFG",
        "type": "float",
        "options_key": "inference_cfg_rate",
        "nested": True,
    },
    "f0_condition": {
        "key": "f0_condition",
        "label": "F0 conditioning",
        "type": "bool",
        "options_key": "f0_condition",
        "nested": True,
    },
    "auto_f0_adjust": {
        "key": "auto_f0_adjust",
        "label": "Auto F0 adjust",
        "type": "bool",
        "options_key": "auto_f0_adjust",
        "nested": True,
    },
    "semi_tone_shift": {
        "key": "semi_tone_shift",
        "label": "Semitone shift",
        "type": "int",
        "options_key": "semi_tone_shift",
        "nested": True,
    },
    "use_pitch_shift": {
        "key": "use_pitch_shift",
        "label": "Use pitch shift",
        "type": "bool",
        "options_key": "use_pitch_shift",
        "nested": True,
    },
    "use_prosody_code": {
        "key": "use_prosody_code",
        "label": "Use prosody code",
        "type": "bool",
        "options_key": "use_prosody_code",
        "nested": True,
    },
    "enable_thinking": {
        "key": "enable_thinking",
        "label": "Enable thinking prompt",
        "type": "bool",
        "options_key": "enable_thinking",
        "nested": True,
    },
    "punctuation": {
        "key": "punctuation",
        "label": "Enable punctuation",
        "type": "bool",
        "options_key": "punctuation",
        "nested": True,
    },
    "lookahead_tokens": {
        "key": "lookahead_tokens",
        "label": "Lookahead tokens",
        "type": "int",
        "options_key": "lookahead_tokens",
        "nested": True,
    },
    "keep_language_tags": {
        "key": "keep_language_tags",
        "label": "Keep language tags",
        "type": "bool",
        "options_key": "keep_language_tags",
        "nested": True,
    },
    "subtalker_temperature": {
        "key": "subtalker_temperature",
        "label": "Subtalker temperature",
        "type": "float",
        "options_key": "subtalker_temperature",
        "nested": True,
    },
    "subtalker_top_k": {
        "key": "subtalker_top_k",
        "label": "Subtalker top-k",
        "type": "int",
        "options_key": "subtalker_top_k",
        "nested": True,
    },
    "subtalker_top_p": {
        "key": "subtalker_top_p",
        "label": "Subtalker top-p",
        "type": "float",
        "options_key": "subtalker_top_p",
        "nested": True,
    },
    "subtalker_do_sample": {
        "key": "subtalker_do_sample",
        "label": "Subtalker sampling",
        "type": "bool",
        "options_key": "subtalker_do_sample",
        "nested": True,
    },
}


def field_spec(key: str, *, nested: bool = False) -> Dict[str, Any]:
    spec = dict(FIELD_SPECS.get(key) or {"key": key, "label": key, "type": "string"})
    if nested:
        spec["nested"] = True
        spec["options_key"] = key
    return spec


def build_field_groups(profile: Dict[str, Any], group_defs: list[tuple]) -> list[Dict[str, Any]]:
    """Build grouped fields from (id, label, description, field_keys) tuples."""
    groups = []
    for group_id, label, description, keys in group_defs:
        fields = [field_spec(key) for key in keys if key in profile.get(f"{group_id}_fields", keys) or key]
        # Simpler: keys is the list directly
        fields = [field_spec(key) for key in keys]
        if fields:
            groups.append(
                {
                    "id": group_id,
                    "label": label,
                    "description": description,
                    "fields": fields,
                }
            )
    return groups
